/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myMapSol from "./MyMap.sol";
export type { myMapSol };
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export type { MyWallet } from "./MyWallet";
