/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myMapSol from "./MyMap.sol";
export { Lock__factory } from "./Lock__factory";
export { MyToken__factory } from "./MyToken__factory";
export { MyWallet__factory } from "./MyWallet__factory";
