{
 "title": "geth",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Go Routines",
   "type": "gauge",
   "description": "Geth で使用されているアクティブなゴルーチンの総数を追跡します。ゴルーチンはGoランタイムによって管理される軽量スレッドで、プロセスの同時実行を可能にします。",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.system/cpu/goroutines.gauge\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"node-0\" or r[\"host\"] == \"node-1\" or r[\"host\"] == \"node-2\" or r[\"host\"] == \"node-3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.system/memory/frees.meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Block header",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/block.gauge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.p2p/peers.gauge\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"node-0\" or r[\"host\"] == \"node-1\" or r[\"host\"] == \"node-2\" or r[\"host\"] == \"node-3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH ingress data rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.p2p/ingress.meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ETH Egress date rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.p2p/egress.meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "READ DISK DATA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.system/disk/readdata.meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DISK DATA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.system/disk/writedata.meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Execute the Transactions in the  Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/execution.timer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Validate to Match Block body and Header",
   "type": "timeseries",
   "description": "Validate block body matches what in the Block Header.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/validation.timer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Write the New Block to the Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"geth\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/account/commits.timer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}